service: util-example

plugins:
  - serverless-plugin-utils
  
custom:
  package_json_version: ${file(./package.json):version}
  version:
    join:
      delimiter: '_'
      values:
        split:
          delimiter: '.'
          value: ${self:custom.package_json_version}
  version_with_underscores: ${self:custom.version}

provider:
  name: aws
  runtime: nodejs10.x